### Goal Objective:
    Goal: Know exactly what data you have, what you don't have, and what you cannot use.

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import openpyxl

### 01 – Dataset Exploration →
 ### Information about the dataset

In [15]:
df = pd.read_excel('../data/sample.xlsx')
df.head()

,Дата заявки,Код заявки,Дата УДЛ клиента,Кредитный продукт,Заявленный официальный доход с анкеты,Менеджер,Запрошенная сумма кредита,Город,БИН работодаетя с отчета с ГЦВП,Просрочки за последние 6 месяцев в днях с кредитной истории ПКБ,Кол-во завершенных займов с кредитной истории ПКБ,Сумма остатка по всем займам с кредитной истории ПКБ,Кол-ао действующих займов клиента кредитной истории ПКБ,Кол-во запросов в ПКБ за последние 30 дней,Срок займа в мес,Признак вызревания CENZ_15_1,FPD_15,Признак вызревания CENZ_15_2,SPD_15,Активная просрочка в днях
0,2022-06-24,KAR.00095934,2006-12-14,Автокредитов,308260.0,Налыбек,2800000,Караганд,NaN,0.0,2.0,2290527.0,3,77.0,NaN,1,0,1,0,0
1,2022-06-23,1003534418,2013-01-10,Кредит налич,270000.0,Уштенова,1500000,Нур-Султ,990240003263/,0.0,9.0,2016655.0,4,36.0,5.0,1,0,1,0,0
2,2022-05-26,BCC_5407,2017-09-20,#картакарта_v,180000.0,Пользователь,70000,Тараз,991040000928/,9.0,4.0,347444.0,2,27.0,11.0,0,0,0,0,0
3,2022-05-15,BCC_1976,2006-08-28,#картакарта_v,800000.0,Пользователь,200000,Алматы,981141001567/,0.0,9.0,6297948.0,10,26.0,6.0,0,0,0,0,0
4,2022-04-29,ALM.00285810,2021-02-19,Автокредитов,600000.0,Мешітбай,11500000,Алматы,890111301342/,2.0,7.0,1974935.0,4,25.0,3.0,1,0,1,0,39

In [16]:
df.shape

(25536, 20)

### Rename the columns to facilitate a more nuanced understanding of the dataset.

In [17]:
rename_map = {
    'Дата заявки': 'application_date',
    'Код заявки': 'application_id',
    'Дата УДЛ клиента': 'client_id_document_date',
    'Кредитный продукт': 'credit_product',
    'Заявленный официальный доход с анкеты': 'declared_official_income',
    'Менеджер': 'manager',
    'Запрошенная сумма кредита': 'requested_loan_amount',
    'Город': 'city',
    'БИН работодаетя с отчета с ГЦВП': 'employer_bin_gcvp',
    'Просрочки за последние 6 месяцев в днях с кредитной истории ПКБ': 'delinquency_days_6m_credit_bureau',
    'Кол-во завершенных займов с кредитной истории ПКБ': 'completed_loans_count_credit_bureau',
    'Сумма остатка по всем займам с кредитной истории ПКБ': 'total_outstanding_balance_credit_bureau',
    'Кол-ао действующих займов клиента кредитной истории ПКБ': 'active_loans_count_credit_bureau',
    'Кол-во запросов в ПКБ за последние 30 дней': 'credit_bureau_inquiries_30d',
    'Срок займа в мес': 'loan_term_months',
    'Признак вызревания CENZ_15_1': 'cenz_15_1_maturity_flag',
    'FPD_15': 'fpd_15',
    'Признак вызревания CENZ_15_2': 'cenz_15_2_maturity_flag',
    'SPD_15': 'spd_15',
    'Активная просрочка в днях': 'active_delinquency_days',
}

df = df.rename(columns=rename_map)

In [18]:
df.columns

Index(['application_date', 'application_id', 'client_id_document_date',
       'credit_product', 'declared_official_income', 'manager',
       'requested_loan_amount', 'city', 'employer_bin_gcvp',
       'delinquency_days_6m_credit_bureau',
       'completed_loans_count_credit_bureau',
       'total_outstanding_balance_credit_bureau',
       'active_loans_count_credit_bureau', 'credit_bureau_inquiries_30d',
       'loan_term_months', 'cenz_15_1_maturity_flag', 'fpd_15',
       'cenz_15_2_maturity_flag', 'spd_15', 'active_delinquency_days'],
      dtype='object')

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25536 entries, 0 to 25535
Data columns (total 20 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   application_date                         25536 non-null  datetime64[ns]
 1   application_id                           25536 non-null  object
 2   client_id_document_date                  25275 non-null  datetime64[ns]
 3   credit_product                           25536 non-null  object
 4   declared_official_income                 25536 non-null  float64
 5   manager                                  25536 non-null  object
 6   requested_loan_amount                    25536 non-null  int64
 7   city                                     25536 non-null  object
 8   employer_bin_gcvp                        21789 non-null  object
 9   delinquency_days_6m_credit_bureau        25045 non-null  float64
 10  completed_loans_count_credit_bureau      25045 non-null  float64
 11  total_outstanding_balance_credit_bureau  25045 non-null  float64
 12  active_loans_count_credit_bureau         25045 non-null  object
 13  credit_bureau_inquiries_30d              25045 non-null  float64
 14  loan_term_months                         21896 non-null  float64
 15  cenz_15_1_maturity_flag                  25536 non-null  int64
 16  fpd_15                                   25536 non-null  int64
 17  cenz_15_2_maturity_flag                  25536 non-null  int64
 18  spd_15                                   25536 non-null  int64
 19  active_delinquency_days                  25536 non-null  int64
dtypes: datetime64[ns](2), float64(6), int64(6), object(6)
memory usage: 3.9+ MB

In [20]:
### Missing Values
print("Missing Value Percentages:")
print(df.isna().mean() * 100)

Missing Value Percentages:
application_date                            0.000000
application_id                              0.000000
client_id_document_date                     1.022086
credit_product                              0.000000
declared_official_income                    0.000000
manager                                     0.000000
requested_loan_amount                       0.000000
city                                        0.000000
employer_bin_gcvp                          14.673402
delinquency_days_6m_credit_bureau           1.922776
completed_loans_count_credit_bureau         1.922776
total_outstanding_balance_credit_bureau     1.922776
active_loans_count_credit_bureau            1.922776
credit_bureau_inquiries_30d                 1.922776
loan_term_months                           14.254386
cenz_15_1_maturity_flag                     0.000000
fpd_15                                      0.000000
cenz_15_2_maturity_flag                     0.000000
spd_15                                      0.000000
active_delinquency_days                     0.000000
dtype: float64

In [23]:
### Duplicated Values
df.duplicated().sum()

0

In [26]:
df.sample(5,random_state=42)

,application_date,application_id,client_id_document_date,credit_product,declared_official_income,manager,requested_loan_amount,city,employer_bin_gcvp,delinquency_days_6m_credit_bureau,completed_loans_count_credit_bureau,total_outstanding_balance_credit_bureau,active_loans_count_credit_bureau,credit_bureau_inquiries_30d,loan_term_months,cenz_15_1_maturity_flag,fpd_15,cenz_15_2_maturity_flag,spd_15,active_delinquency_days
2281,2022-04-29,1003149831,2021-08-17,Рефинансиров,250000.0,Егембердиева,1478908,Шымкент,100540004873/,0.0,0.0,478907.0,1,4.0,6.0,1,0,1,0,0
17521,2022-06-20,1003501173,2013-01-03,Кредит налич,150000.0,Ќамбар,300000,Алматы,990540004827/,0.0,10.0,1510745.0,2,0.0,10.0,1,0,1,0,0
8779,2022-04-19,KAR.00090659,2009-02-17,Автокредитов,1500000.0,Налыбек,5600000,Караганд,NaN,0.0,3.0,4699601.0,4,1.0,NaN,1,0,1,0,0
7251,2022-06-27,ATB.00068191,2015-09-26,Ипотека,218764.0,Бугыбаева,6640000,Актобе,020540001554/,0.0,2.0,215616.0,1,2.0,6.0,1,0,1,0,0
12528,2022-04-11,1003015671,2016-01-05,Кредит налич,0.0,Айтбайќызы,1200000,Кызылорд,150340008622/,0.0,3.0,148919.0,3,1.0,6.0,1,0,1,0,0